import type { PlantEntry, UserRecommendationSettings } from "./types";

const now = "2026-05-12T07:30:00.000Z";

export const mockEntries: PlantEntry[] = [
  {
    id: "entry_camellia",
    originalImageUrl: "/images/mock/camellia-original.jpg",
    generatedImageUrl: "/images/mock/camellia-atlas.jpg",
    speciesName: "Camellia japonica",
    commonName: "山茶",
    identificationStatus: "identified",
    confidence: 0.88,
    notes: "雨后的一株山茶，花开洁白，香气淡雅。",
    latitude: 30.2475,
    longitude: 120.1215,
    locationName: "浙江省杭州市西湖区满觉陇路",
    publicLocationLabel: "杭州",
    weatherSummary: "小雨后",
    capturedAt: "2026-05-20T10:30:00.000Z",
    createdAt: now,
    updatedAt: now,
    styleMode: "scientific_herbarium",
    tags: ["庭院植物", "开花植物", "常绿灌木"],
    favorite: true,
    visibility: "recommendable",
    ownerDisplayName: "Luna's Herbarium",
    generationHistory: []
  },
  {
    id: "entry_hydrangea",
    originalImageUrl: "/images/mock/hydrangea-original.jpg",
    generatedImageUrl: "/images/mock/hydrangea-atlas.jpg",
    speciesName: "Hydrangea macrophylla",
    commonName: "绣球花",
    identificationStatus: "identified",
    confidence: 0.81,
    notes: "花球颜色从粉到紫，适合作为图鉴封面。",
    latitude: null,
    longitude: null,
    locationName: "Grandma's Backyard",
    publicLocationLabel: "庭院",
    weatherSummary: null,
    capturedAt: "2026-05-18T09:12:00.000Z",
    createdAt: now,
    updatedAt: now,
    styleMode: "minimal_japanese_field_guide",
    tags: ["花园", "夏季", "粉紫"],
    favorite: false,
    visibility: "recommendable",
    ownerDisplayName: "Moss & Petal",
    generationHistory: []
  },
  {
    id: "entry_lavender",
    originalImageUrl: "/images/mock/lavender-original.jpg",
    generatedImageUrl: "/images/mock/lavender-atlas.jpg",
    speciesName: "Lavandula angustifolia",
    commonName: "薰衣草",
    identificationStatus: "identified",
    confidence: 0.79,
    notes: "城市花坛里一丛淡紫色的薰衣草。",
    latitude: null,
    longitude: null,
    locationName: "Tokyo Riverside",
    publicLocationLabel: "Tokyo",
    weatherSummary: "晴",
    capturedAt: "2026-05-15T16:20:00.000Z",
    createdAt: now,
    updatedAt: now,
    styleMode: "modern_editorial",
    tags: ["香草", "紫色", "城市漫步"],
    favorite: false,
    visibility: "recommendable",
    ownerDisplayName: "Flora Archive",
    generationHistory: []
  },
  {
    id: "entry_rose",
    originalImageUrl: "/images/mock/rose-original.jpg",
    generatedImageUrl: "/images/mock/rose-atlas.jpg",
    speciesName: "Rosa chinensis",
    commonName: "月季",
    identificationStatus: "edited",
    confidence: 0.74,
    notes: "河岸边的黄色月季。",
    latitude: null,
    longitude: null,
    locationName: "Tokyo Riverside",
    publicLocationLabel: "Tokyo",
    weatherSummary: "晴",
    capturedAt: "2026-05-10T16:20:00.000Z",
    createdAt: now,
    updatedAt: now,
    styleMode: "vintage_botanical_book",
    tags: ["黄色", "河岸", "旅行"],
    favorite: true,
    visibility: "private",
    ownerDisplayName: null,
    generationHistory: []
  },
  {
    id: "entry_fern",
    originalImageUrl: "/images/mock/fern-original.jpg",
    generatedImageUrl: "/images/mock/fern-atlas.jpg",
    speciesName: "Nephrolepis exaltata",
    commonName: "肾蕨",
    identificationStatus: "unidentified",
    confidence: null,
    notes: "阴影下的蕨类，叶片很细密。",
    latitude: null,
    longitude: null,
    locationName: "Botanic Gardens Singapore",
    publicLocationLabel: "Singapore",
    weatherSummary: "潮湿",
    capturedAt: "2026-05-08T08:10:00.000Z",
    createdAt: now,
    updatedAt: now,
    styleMode: "minimal_japanese_field_guide",
    tags: ["蕨类", "阴生", "未识别"],
    favorite: false,
    visibility: "private",
    ownerDisplayName: null,
    generationHistory: []
  },
  {
    id: "entry_lotus",
    originalImageUrl: "/images/mock/lotus-original.jpg",
    generatedImageUrl: "/images/mock/lotus-atlas.jpg",
    speciesName: "Nelumbo nucifera",
    commonName: "荷花",
    identificationStatus: "identified",
    confidence: 0.86,
    notes: "湖边的粉色荷花。",
    latitude: null,
    longitude: null,
    locationName: "杭州西湖",
    publicLocationLabel: "杭州",
    weatherSummary: "多云",
    capturedAt: "2026-05-05T11:30:00.000Z",
    createdAt: now,
    updatedAt: now,
    styleMode: "scientific_herbarium",
    tags: ["水生植物", "粉色", "夏季"],
    favorite: false,
    visibility: "private",
    ownerDisplayName: null,
    generationHistory: []
  }
];

export const recommendationSettings: UserRecommendationSettings = {
  userId: "user_demo",
  recommendationSharingEnabled: false,
  defaultEntryVisibility: "private",
  publicDisplayName: "My Herbarium",
  updatedAt: now
};

export function getRecommendableEntries(entries: PlantEntry[] = mockEntries): PlantEntry[] {
  return entries.filter((entry) => entry.visibility === "recommendable");
}
